modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "yaclsynced"
version = "${version}-neoforge"
displayName = "YACLSynced"
authors = "Tigercrl"
description = '''
An addon for YetAnotherConfigLib with server-client config synchronization
'''
logoFile = "assets/yaclsynced/icon.png"
updateJSONURL = "https://api.modrinth.com/updates/yacl-synced/forge_updates.json"
displayURL = "https://modrinth.com/mod/yacl-synced"

[[dependencies.yaclsynced]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yaclsynced]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "yaclsynced.mixins.json"
